sonar.projectKey=Webdevoo_webdevoo-lead
sonar.organization=Webdevoo

# Chemins des sources de ton application Nuxt 4
sonar.sources=app,components,layouts,pages,server,composables,utils

# Exclusions pour éviter d'analyser les dossiers de build ou les dépendances
sonar.exclusions=**/node_modules/**,**/.output/**,**/dist/**,**/.nuxt/**

# Intégration du rapport de couverture de tests (généré par Vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info