sonar.projectKey=Webdevoo_webdevoo-lead
sonar.organization=Webdevoo

# Chemins des sources de ton application Nuxt 4
sonar.sources=app,server,shared

# Exclusions pour ignorer les dossiers de build, dépendances et rapports de test
sonar.exclusions=**/node_modules/**,**/.output/**,**/dist/**,**/.nuxt/**,**/coverage/**,**/playwright-report/**,**/test-results/**

# Intégration du rapport de couverture de tests (généré par Vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info